### ISSUE TITLE
pg15-3.4.0 is available, but autoupdate doesn't seem to not recognize it

### ISSUE THREAD

**Issue by ShadowCreator250** [wale/scoop-bucket#1]
see https://download.osgeo.org/postgis/windows/pg15/

but the manifest is still at pg15-3.3.3: https://github.com/wale/scoop-bucket/blob/master/bucket/postgis.json

**Comment by wale** [comment]
Fixed by https://github.com/wale/scoop-bucket/commit/f5d8b5af034b84c0dcaf2a627d2a343ed26a12d2 and https://github.com/wale/scoop-bucket/commit/963b7a292fd347718d2e981842c08d98679d5577.

Closing this issue.
